### ISSUE TITLE
Very unhelpful error when running analyzer code on jurisdiction with no data

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#146]
For example, when running `analyzer.bar('2020 Primary', 'Illinois')` (when no such data is loaded) gives this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eric/Desktop/election_data_analysis/src/election_data_analysis/__init__.py", line 1296, in bar
    False,
  File "/Users/eric/Desktop/election_data_analysis/src/election_data_analysis/analyze/__init__.py", line 285, in create_bar
    session, election_id, top_ru_id, subdivision_type_id
  File "/Users/eric/Desktop/election_data_analysis/src/election_data_analysis/database/__init__.py", line 1309, in get_candidate_votecounts
    result_df.columns = result.keys()
  File "/Users/eric/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 5143, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/eric/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 564, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Users/eric/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 0 elements, new values have 20 elements
```

Provide more helpful error and/or simply return `None`.

**Comment by ericmtsai** [comment]
These errors can cause problems with the [flask code](https://electionanomaly.slack.com/archives/C017ABXLM5H/p1601964057122400) as well, making this a high priority for November.
