### ISSUE TITLE
Error loading MI data to VV server

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#192]
Loading Michigan data on the Verified Voting server gives this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/election_data_analysis-1.0-py3.7.egg/election_data_analysis/__init__.py", line 218, in load_all
    juris[jp],
  File "/usr/local/lib/python3.7/site-packages/election_data_analysis-1.0-py3.7.egg/election_data_analysis/__init__.py", line 453, in check_and_init_singledataloader
    if ui.fatal_error(new_err):
  File "/usr/local/lib/python3.7/site-packages/election_data_analysis-1.0-py3.7.egg/election_data_analysis/user_interface/__init__.py", line 831, in fatal_error
    error_type_list = err.keys()
AttributeError: 'tuple' object has no attribute 'keys'
```

**Comment by ericmtsai** [comment]
@Raghu-Srungavarapu assigned you to look into this, please. MI works for me locally but not on the server, not sure why.

**Comment by ericmtsai** [comment]
This was user error and is working now.
