### ISSUE TITLE
MEDIUM-CountItemTypes besides `total` do not seem to be working in scatter

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#203]

**Comment by ericmtsai** [comment]
```>>> analyzer.scatter('Georgia', 'county', '2018 General', 'absentee-mail candidates', 'Stacey Abrams', '2018 General', 'election-day candidates', 'Stacey Abrams')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/election_data_analysis-1.0-py3.7.egg/election_data_analysis/__init__.py", line 1301, in scatter
    h_count_id,
UnboundLocalError: local variable 'h_count_id' referenced before assignment```
