### ISSUE TITLE
Create softer/more detailed error for incorrect contest name

### ISSUE THREAD

**Issue by wonderbug2020** [ElectionDataAnalysis/election_data_analysis#208]
E.G. For california, I had the spelling/syntax for the presidential race entered incorrectly. The error I received is shown below. This is not very helpful for diagnosing the issue. 

correct spelling/syntax "CandidateContest	US President (CA) (Democratic Party)	President Democratic"

`Processing 2020_presidential_primary.xls
invalid input syntax for type integer: ""
CONTEXT:  COPY __temp_insert_postgres_20201007_142816_263970, line 1, column Election_Id: ""
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wolgy\anaconda3\lib\site-packages\election_data_analysis-1.0-py3.8.egg\election_data_analysis\__init__.py", line 222, in load_all
    load_error = sdl.load_results()
  File "C:\Users\wolgy\anaconda3\lib\site-packages\election_data_analysis-1.0-py3.8.egg\election_data_analysis\__init__.py", line 360, in load_results
    results_info, e = self.track_results()
  File "C:\Users\wolgy\anaconda3\lib\site-packages\election_data_analysis-1.0-py3.8.egg\election_data_analysis\__init__.py", line 346, in track_results
    e = db.insert_to_cdf_db(self.session.bind, data, "_datafile")
  File "C:\Users\wolgy\anaconda3\lib\site-packages\election_data_analysis-1.0-py3.8.egg\election_data_analysis\database\__init__.py", line 538, in insert_to_cdf_db
    cursor.execute(q)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block`

**Comment by sfsinger19103** [comment]
The error messages were caused by a spelling error in the `*.ini` file for `2020_presidential_primary.xls`. If the parameter election has a value that is not in Election.txt, then `track_results()` will fail.
