### ISSUE TITLE
Ugly fails in Analyzer.scatter()

### ISSUE THREAD

**Issue by sfsinger19103** [ElectionDataAnalysis/election_data_analysis#491]
```>>> analyzer.scatter("Philadelphia;Ward 64","2011 Primary","Candidate total","Stephanie Singer","2011 Primary","Candidate total","Margaret M Tartaglione", fig_type='svg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/election_data_analysis-1.0-py3.8.egg/election_data_analysis/__init__.py", line 1545, in scatter
    viz.plot("scatter", agg_results, fig_type, self.rollup_directory)
  File "/usr/local/lib/python3.8/site-packages/election_data_analysis-1.0-py3.8.egg/election_data_analysis/visualize/__init__.py", line 52, in plot
    os.mkdir(image_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/singer3/Documents/rollups/images'
```

and some requirements:
- pustil
- requests

and a seemingly impossible requirement:
- orca -- installation failed on Stephanie's mac because mac did not recognize the developer so refused to install (however, installation succeeded after repeated attempts, weird)

**Comment by sfsinger19103** [comment]
Closed (see #546)
