### ISSUE TITLE
Jurisdiction and template files not accessible relative to project root

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#77]
If the app is run from inside the repository, there are no issues. But if it's run from "out in the wild", you may get this error:
```
>>> jp.new_juris_files()
Starting new_juris_files
Directory created: /Users/singer3/PycharmProjects/election_data_analysis/src/jurisdictions/Indiana
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/election_data_analysis-0.1-py3.8.egg/election_data_analysis/__init__.py", line 432, in new_juris_files
    error = jm.ensure_jurisdiction_dir(self.d["jurisdiction_path"])
  File "/usr/local/lib/python3.8/site-packages/election_data_analysis-0.1-py3.8.egg/election_data_analysis/juris_and_munger/__init__.py", line 321, in ensure_jurisdiction_dir
    err = ensure_juris_files(juris_path, ignore_empty=ignore_empty)
  File "/usr/local/lib/python3.8/site-packages/election_data_analysis-0.1-py3.8.egg/election_data_analysis/juris_and_munger/__init__.py", line 350, in ensure_juris_files
    template_list = [x[:-4] for x in os.listdir(templates_dir)]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/election_data_analysis-0.1-py3.8.egg/templates/jurisdiction_templates'
```
This occurs because the directory that holds the template files live outside the built package's directory structure.

Since these files are directly relevant to building the jurisdiction and munger, this issue proposes moving those template files into the `juris_and_munger` module.

**Comment by ericmtsai** [comment]
Closed by #68
